import { Language } from './types';

export const t = {
  en: {
    subtitle: "Explore Curated AI Generation Prompts",
    searchPlaceholder: "Search by title, prompt, or author...",
    noArtworks: "No artworks found matching your criteria.",
    clearFilters: "Clear all filters",
    generatedBy: "Generated by",
    promptTitle: "Prompt",
    copyPrompt: "Copy Prompt",
    copied: "Copied!",
    like: "Like",
    unlike: "Unlike",
    submit: "Submit",
    github: "GitHub",
    allModels: "All Models",
    modelFilter: "Model",
    categoryMap: {
      "All": "All",
      "Favorites": "Favorites",
      "人像写真": "Portrait",
      "场景插画": "Scene Illustration",
      "头像插画": "Avatar Illustration",
      "平面设计": "Graphic Design",
      "产品陈列": "Product Display",
      "童趣角色": "Playful Characters",
      "出版漫画": "Comics",
      "空间建筑": "Architecture",
      "风格实验": "Style Experiment",
      "东方美学": "Oriental Aesthetics",
      "手绘质感": "Handmade Texture"
    } as Record<string, string>
  },
  zh: {
    subtitle: "探索精选 AI 生成提示词",
    searchPlaceholder: "按标题、提示词或作者搜索...",
    noArtworks: "没有找到符合条件的展品。",
    clearFilters: "清除所有过滤条件",
    generatedBy: "生成工具：",
    promptTitle: "提示词 (Prompt)",
    copyPrompt: "复制提示词",
    copied: "已复制",
    like: "加入收藏",
    unlike: "取消收藏",
    submit: "投稿",
    github: "GitHub仓库",
    allModels: "全部模型",
    modelFilter: "生成模型",
    categoryMap: {
      "All": "全部",
      "Favorites": "收藏",
      "人像写真": "人像写真",
      "场景插画": "场景插画",
      "头像插画": "头像插画",
      "平面设计": "平面设计",
      "产品陈列": "产品陈列",
      "童趣角色": "童趣角色",
      "出版漫画": "出版漫画",
      "空间建筑": "空间建筑",
      "风格实验": "风格实验",
      "东方美学": "东方美学",
      "手绘质感": "手绘质感"
    } as Record<string, string>
  }
};
